/*
  # Add GPT Tags to Products Table

  1. Changes
    - Add `gpt_tags` column to `products` table
    - Stores comma-separated GPT-generated product tags

  2. Details
    - Column: `gpt_tags` (text, nullable)
    - Tags are generated by OpenAI GPT based on product title, description, features
    - Tags include functionality, room/usage, and style/material keywords
    - Example: "standing desk, adjustable desk, home office, modern office, ergonomic furniture"
*/

-- Add gpt_tags column to products table
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'products' AND column_name = 'gpt_tags'
  ) THEN
    ALTER TABLE products ADD COLUMN gpt_tags text DEFAULT NULL;

    COMMENT ON COLUMN products.gpt_tags IS 'GPT-generated product tags (comma-separated). Includes functionality, room/usage, and style/material keywords for SEO and filtering.';
  END IF;
END $$;
