name: Auto PR from Prompt

on:
  workflow_dispatch:   # lets you click "Run workflow" in GitHub

jobs:
  make-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Read your prompt from a file in the repo and ask the AI for changes
      - name: Generate patch from prompt
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          echo "Using prompt in .prompt.txt"
          # Install a tiny helper
          npm init -y >/dev/null 2>&1 || true
          npm install node-fetch@3 >/dev/null 2>&1
          node -e '
            import fs from "fs";
            import fetch from "node-fetch";
            const prompt = fs.readFileSync(".prompt.txt","utf8");
            (async ()=>{
              const res = await fetch("https://api.openai.com/v1/chat/completions", {
                method: "POST",
                headers: {
                  "Authorization": `Bearer ${process.env.OPENAI_API_KEY}`,
                  "Content-Type": "application/json"
                },
                body: JSON.stringify({
                  model: "gpt-4o-mini",
                  messages: [{role:"user", content:
                    "Return a unified diff patch. Only output the diff. Prompt:\n\n"+prompt
                  }],
                  temperature: 0.2,
                  max_tokens: 4000
                })
              });
              const json = await res.json();
              const patch = json.choices?.[0]?.message?.content || "";
              fs.writeFileSync("patch.diff", patch);
            })();
          '

      - name: Apply patch (ignore if empty)
        run: |
          git config user.name "Auto Codegen Bot"
          git config user.email "bot@example.com"
          git checkout -b auto/fix-$(date +%s)
          if [ -s patch.diff ]; then git apply patch.diff || true; fi
          git add -A
          git commit -m "Auto patch from .prompt.txt" || echo "No changes to commit"
          git push origin HEAD

      - name: Open Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          title: "Auto-generated PR from .prompt.txt"
          body: "This PR was generated by the Auto PR workflow."
          branch: ${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
