name: Test OpenAI Secret

on:
  workflow_dispatch: # lets you trigger manually

jobs:
  test-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Print confirmation
        run: echo "OPENAI_API_KEY is set and length is ${#OPENAI_API_KEY}"
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
